[package]
name = "akasha"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = "0.1.17"
futures = "0.3.31"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"